### ISSUE TITLE
Missing astran.cfg

### ISSUE THREAD

**Issue by leoheck** [aziesemer/astran#36]
I installed Astran for all users in our lab as a regular CAD tool. In this way, the users can use astran anywhere they are and not only from the instalation folder.

The problem with this is related to where Astran look for it own files and configurations. Take a look:
![astran - gme-ufrgs_028](https://cloud.githubusercontent.com/assets/1277920/10289892/4f313ba2-6b77-11e5-8179-af6041cebda4.png)

This problem is easly fixed creating a environment variable like __ASTRAN_PATH__, which Astran can use to search for the files. This can also be used to fix the [issue #35] (https://github.com/aziesemer/astran/issues/35). 

That solution can also be used to __improve__ the initial __astran.cfg__ file like this: 

```
set viewer "${ASTRAN_PATH}/Tools_MacIntel/wxSightGL.app/Contents/MacOS/wxSightGL"
set rotdl "${ASTRAN_PATH}/Tools_MacIntel/rotdl"
set placer "${ASTRAN_PATH}/Tools_MacIntel/mobralplace"
set lpsolve "${GUROBI_PATH}/bin/gurobi_cl"
set log history.log
set verbose_mode 1
```

With this solution, it is possible to change the astran lpsolver easly changin the __GUROBI_PATH__ variable.

Please, consider to improve the astran to make it more flexible and professional with this feature. If you need help, I can try to help you with this feature.

**Comment by aziesemer** [comment]
Vou ver se consigo.

**Comment by leoheck** [comment]
Ai tu ia mandar bem!! :+1:

**Comment by leoheck** [comment]
Ah, isso não impede de, se a variavel não tiver configurada, como última instância, deixar o Astran procurar as coisas do jeito que ele faz atualmente. Isso é bem fácil de fazer.

**Comment by leoheck** [comment]
Adriel, tomei a iniciativa e implementei o inicio do processo de aceitar variaveis de ambiente. Dá uma olhada. Se a variavel  ```ASTRAN_PATH``` nao tiver configurada ele funciona da mesma forma como funcionava. Se tiver configurada ele procura o astran.cfg de ```${ASTRAN_PATH}/bin/astran.cfg```. Tá funcionando legal. Ah, eu corrigi um problema do teu ultimo commit que nao compilava, referente a tua implementação do --help. Mudei o makefile pra ele identificar se é Mac OSX ou Linux, ai só precisa de um makefile. O próximo passo é o teu parser reconhecer variaveis no formato ${VAR} ou $VAR pra ele expandir elas.. ai é possivel ter vas variaveis de ambiente dentro do astran.cfg ou de qualquer script/comando. Vai ficar excelente.

**Comment by leoheck** [comment]
Tá funcionando, executei o Astran do /tmp e ta usando o ASTRAN_PATH :)

![astran - gme-ufrgs_006](https://cloud.githubusercontent.com/assets/1277920/10384887/7a01af62-6e18-11e5-8d2b-1e9c9b779d6e.jpg)

**Comment by aziesemer** [comment]
Valeu!
Não cheguei a testar o --help direito hehehe como disse, não rodo ele por
linha de comando ;)

**Comment by leoheck** [comment]
Ah, que maneiro o comentário do teu último post, delirei hehe  :)

--
Leandro Sehnem Heck

**Comment by aziesemer** [comment]
:)

2015-10-09 13:13 GMT-03:00 Leandro Heck <notifications@github.com>:
