### ISSUE TITLE
Astran commands

### ISSUE THREAD

**Issue by leoheck** [aziesemer/astran#38]
Where I can find a help with all the Astran commands?

**Comment by aziesemer** [comment]
Digitando help na barra de comandos embaixo na janela principal :P

**Comment by leoheck** [comment]
Valeu! Assim, fica documentado aqui já!

**Comment by leoheck** [comment]
Mas dá pra ir no readme da primeira página do git! 
Se quiser eu atualizo pra dar mais unformações pros forateiros :)

**Comment by leoheck** [comment]
Outra coisa, como vejo os parâmetros que o Astran aceita na linha de comando?

**Comment by leoheck** [comment]
Existe um: ```Astran --help``` ?

**Comment by leoheck** [comment]
Tem como eu executar o astran direto na linha de comando? Eu pensei que eu tinha feito isso uma vez, mas não consegui fazer denovo.

**Comment by aziesemer** [comment]
Pode atualizar sim.
Por linha de comando acho que não. Só se executar o shell da ferramenta. Para fazer isto é só digitar: Astran --shell
