### ISSUE TITLE
Tech rule improvement

### ISSUE THREAD

**Issue by leoheck** [aziesemer/astran#39]
É possivel aidicionar uma forma de ignorar comentários no arquivo de teconlogia? Isso facilita o processo de portar/modifica/adaptar esse arquivo. Normalmente ele ignora os comandos que nao entende, mas se achar o caractere de comentário, (por exemplo ```#```) ele pode simplesmente evitar dizer essa informação na tela.

**Comment by aziesemer** [comment]
Comentários no arquivo de regras começa com *
Implementei suporte a comentários no interpretador de linha de comando
também, pode ser útil no caso dos scripts

2015-10-05 23:13 GMT-03:00 Leandro Heck <notifications@github.com>:

**Comment by leoheck** [comment]
Boa, valeu!

--
Leandro Sehnem Heck

2015-10-06 9:36 GMT-03:00 aziesemer <notifications@github.com>:
