### ISSUE TITLE
Status da finalização do Astran 

### ISSUE THREAD

**Issue by leoheck** [aziesemer/astran#40]
O Astran retorna 1 quando termina. Isso tá ok Adriel? Aqui no linux estou esperando um 0.

**Comment by aziesemer** [comment]
Fixed!

**Comment by aziesemer** [comment]
hehehe, eu só utilizo o Astran pela GUI, e nela não tinha este erro. Ele só
se manifesta quando encerra o Astran com o comando EXIT, coisa que eu nunca
fazia. :)

**Comment by leoheck** [comment]
E nós só usamos por linha de comando! Maneiro, ta ficando uma ferramenta bem robusta.
