### ISSUE TITLE
Unable to generate cells due to lp_solve error

### ISSUE THREAD

**Issue by xiayu87** [aziesemer/astran#47]
While generating cell layout I'm getting this error at command compact layout:

> Error, Unable to open input file 'TimeLimit=3600'
> Usage of ../Tools_Linux/lp_solve version 5.5.2.0:
> ../Tools_Linux/lp_solve [options] [[<]input_file]
> List of options:
> -h              prints this message
> -lp             read from LP file (default)
> -mps            read from MPS file, default in fixed format
> -mps_free               use free format
> -mps_ibm                interprete integers accoring to ibm format
> -mps_negobjconst        negate objective constant
> -fmps           read from MPS file in free format
> -rpar filename  read parameters from filename.

Any workaround or solution?

Thanks in advance

**Comment by aziesemer** [comment]
Are you using Gurobi or lpsolve?

**Comment by xiayu87** [comment]
I'm using lp_solve on Ubuntu 16.04

**Comment by aziesemer** [comment]
We migrated everything to Gurobi since lpsolve is unable to solve our models in a feasible time.

**Comment by xiayu87** [comment]
Thank you. This works great and faster.
