### ISSUE TITLE
Gurobi 9.5 support?

### ISSUE THREAD

**Issue by zslwyuan** [aziesemer/astran#54]
Hi Adriel @aziesemer ,

Thanks a lot for your excellent work! Recent Gurobi stops providing the download link of Gurobi 5.0 and now people can only find Gurobi 8.0-9.5. I am resolving the problem and a PR will be submitted.

**Comment by aziesemer** [comment]
Hello, thanks for your interest in Astran.
I'm not maintaining it anymore, but I asked some ASTRAN users about issues with Gurobi and it seems that it was restricted to Gurobi 6 to 7 or 8. They said that they did not have issues with recent Gurobi versions.
The issue that you reported does not seem to be related to Gurobi. The problem with Gurobi 6 was that the "feasible" solution was actually invalid (not legal), which is different from not finding a solution.
Unfeasible solutions more commonly happen when the cell is too complex and it is not possible to arrange the routing tracks. A workaround is to make the generation more conservative, run it again (maybe with a different transistor placement or routing solution it will be able to complete the compaction step), add more routing tracks/increase cell height,...

**Comment by zslwyuan** [comment]
Hi @aziesemer ,

Thanks a lot for your prompt reply and I agree that the problem is not the version of Gurobi but our rule settings. Thanks agian! ^_^.
